[package]
name = "quirc-rs"
version = "0.1.0"
authors = ["Szabolcs Berecz <szabolcs.berecz@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
chrono = "0.4.6"
clap = "2.32.0"
image = "0.21.0"
libc = "0.2.49"
