[package]
name = "test-utils"
version = "0.1.0"
authors = ["Szabolcs Berecz <szabolcs.berecz@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23"
libc = "0.2.49"
quirc-rs = { path = ".." }
quirc-wrapper = { path = "../quirc-wrapper" }
